{% set build = 0 %}
{% set version = '2016.2.1' %}

package:
  name: pytools
  version: {{version}}

about:
  home: http://pypi.python.org/pypi/pytools
  license: MIT License
  summary: "A collection of tools for Python."

source:
  fn: pytools-{{version}}.tar.gz
  url: https://pypi.python.org/packages/1a/1e/ce42d53bad97ad16732c8d9ac1dd6ed22a906ea07f291df5f6f90a6c7a2a/pytools-{{version}}.tar.gz
  md5: 452dfa3023733a675cc1bee91c536cbd

requirements:
  build:
    - appdirs >=1.4.0
    - decorator >=3.2.0
    - python
    - setuptools
    - six >=1.8.0
    - numpy >=1.6.0

  run:
    - appdirs >=1.4.0
    - decorator >=3.2.0
    - python
    - six >=1.8.0
    - numpy >=1.6.0

build:
  number: {{build}}
  script: python setup.py install
