{%set build = 0 %}

package:
  name: pytools
  version: !!str 2013.5.7

about:
  home: https://github.com/jab/bidict
  license: MIT License
  summary: "A collection of tools for Python."

source:
  fn: pytools-2013.5.7.tar.gz
  url: https://pypi.python.org/packages/source/p/pytools/pytools-2013.5.7.tar.gz
  md5: 8954a655749d646d456335b93aad3caf

requirements:
  build:
    - 'decorator >=3.2.0'
    - python
    - setuptools

  run:
    - python

build:
  number: {{build}}
  script: python setup.py install
