{%set build = 0 %}
{%set version = '2013.5.7' %}

package:
  name: pytools
  version: {{version}}

about:
  home: http://pypi.python.org/pypi/pytools
  license: MIT License
  summary: "A collection of tools for Python."

source:
  fn: pytools-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/p/pytools/pytools-{{version}}.tar.gz
  md5: 8954a655749d646d456335b93aad3caf

requirements:
  build:
    - 'decorator >=3.2.0'
    - python
    - setuptools

  run:
    - 'decorator >=3.2.0'
    - python

build:
  number: {{build}}
  script: python setup.py install
