{% set build = 0 %}
{% set version = '2015.1.6' %}

package:
  name: pytools
  version: {{version}}

about:
  home: http://pypi.python.org/pypi/pytools
  license: MIT License
  summary: "A collection of tools for Python."

source:
  fn: pytools-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/p/pytools/pytools-{{version}}.tar.gz
  md5: 2942235bcff7369a00882b29c6bcc3e4

requirements:
  build:
    - 'appdirs >=1.4.0'
    - 'decorator >=3.2.0'
    - python
    - setuptools
    - 'six >=1.8.0'

  run:
    - 'appdirs >=1.4.0'
    - 'decorator >=3.2.0'
    - python
    - 'six >=1.8.0'

build:
  number: {{build}}
  script: python setup.py install
