{% set build = 0 %}
{% set version = '2015.1.3' %}

package:
  name: pytools
  version: {{version}}

about:
  home: http://pypi.python.org/pypi/pytools
  license: MIT License
  summary: "A collection of tools for Python."

source:
  fn: pytools-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/p/pytools/pytools-{{version}}.tar.gz
  md5: 3793467d8feaaf3db99b3948d749f562

requirements:
  build:
    - 'appdirs >=1.4.0'
    - 'decorator >=3.2.0'
    - python
    - setuptools
    - six

  run:
    - 'appdirs >=1.4.0'
    - 'decorator >=3.2.0'
    - python
    - six

build:
  number: {{build}}
  script: python setup.py install
